### ISSUE TITLE
AttributeError: 'BERT' object has no attribute 'extracts_v2'

### ISSUE THREAD

**Issue by SeekPoint** [seriousran/BERT-embedding#8]
ub16c9@ub16c9-gpu:/media/ub16c9/fcd84300-9270-4bbd-896a-5e04e79203b7/ub16_prj/BERT-embedding$ python3.6 bert_embedding.py
WARNING: Logging before flag parsing goes to stderr.
W0709 22:00:20.136421 140414935418624 __init__.py:308] Limited tf.compat.v2.summary API due to missing TensorBoard installation.
W0709 22:00:20.175361 140414935418624 deprecation_wrapper.py:119] From bert_embedding.py:11: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

W0709 22:00:20.175547 140414935418624 deprecation_wrapper.py:119] From bert_embedding.py:11: The name tf.logging.ERROR is deprecated. Please use tf.compat.v1.logging.ERROR instead.

Traceback (most recent call last):
  File "bert_embedding.py", line 169, in <module>
    results = bert.extracts_v2(sentences)
AttributeError: 'BERT' object has no attribute 'extracts_v2'
ub16c9@ub16c9-gpu:/media/ub16c9/fcd84300-9270-4bbd-896a-5e04e79203b7/ub16_prj/BERT-embedding$

**Comment by seriousran** [comment]
Function 'extracts_v2' is renamed as extracts.
But "bert_embedding.py" was not.
I've updated "bert_embedding.py" file with that. Thanks :)

**Comment by seriousran** [comment]
Sorry for closing on my own...
